# Generated by Django 6.0.2 on 2026-02-13 12:07

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, help_text="User's email address", max_length=150, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(help_text="User's first name", max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(help_text="User's last name", max_length=150, verbose_name='Last name')),
                ('avatar', models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='images/avatars/', verbose_name='Avatar')),
                ('password', models.CharField(help_text="User's hash representation of the password", max_length=254, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password')),
                ('is_staff', models.BooleanField(default=False, help_text='True if the user is an admin and has an access to the admin panel', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='True if the user is active and has an access to request data', verbose_name='Active status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='The date and time when the user account was created', verbose_name='Date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
